### ISSUE TITLE
Is it intentional for the Math to be wrong?

### ISSUE THREAD

**Issue by vilsbole** [status-im/the-explainers#17]
This article on [Randomness](https://github.com/status-im/the-explainers/blob/master/authors/swader/09-randomness/en_US/final.md it provides) contains a few errors that distract from it's content:

1.
> (((((25^2)^2)^2)^2)^2)^2 =
>  ~~((((225^2)^2)^2)^2)^2 =~~

((((**625**^2)^2)^2)^2)^2 =

2. 
> One epoch in Ethereum 2.0 is 6.4 minutes. [...] This comes down to 16 VDFs - and thereby 16 random numbers - per hour.

per VDF period of 102.4 minutes?

**Comment by Swader** [comment]
Not intentional, I'm just an idiot who rushes into publication with too few reviews 🤦‍♂️
Thanks, fixed now and applied to live version!
